### ISSUE TITLE
Reaction directionality

### ISSUE THREAD

**Issue by jchitpin** [stelmo/Escher.jl#3]
Is it possible to preserve reaction directionality when plotting metabolic models with `escherplot!()` using `arrows!` instead of `lines!`?

**Comment by stelmo** [comment]
Hi there,

Yes, that is a good idea! I will implement that this weekend :)

**Comment by stelmo** [comment]
I just added arrows to the plot. Could you test it out and let me know what you think (v0.5.0)? Note, the arrows are not drawn at the tips of the reaction edges, but slightly further down, I think this looks better (and was substantially easier to implement). If the updated package doesn't work, lmk, Makie just released a new version as well, so there is a small chance that things could go wrong...

**Comment by jchitpin** [comment]
Thanks! I'm new to COBREXA so it will take me a bit to figure out where reaction directionality is stored in the model JSON file. Then I'll close off this issue.

**Comment by jchitpin** [comment]
I forgot to update to (v0.5.0) at first but  can confirm the reaction arrows work and look great trailing behind the metabolite nodes.  Manually specifying reversibility with `reaction_directions` also worked as expected. Thanks again!
